version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - web
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 3
